#!/bin/bash

JSON_FIELDS="createdAt,labels,number,title"
TEMPLATE='
  {{- printf "Showing issues to triage\n\n" -}}
  {{- tablerow "ID" "TITLE" "LABELS" "CREATED AT" -}}
  {{- range $issue := . -}}
    {{- $found := false -}}
    {{- range $index, $label := $issue.labels -}}
      {{- if not $found -}}
        {{- if eq $label.name "p1" "p2" "p3" "core" "help wanted" "tracking issue" "needs-design" "blocked" "needs-user-input" -}}
          {{- $found = true -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
    {{- if not $found -}}
      {{- $number := printf "#%v" $issue.number | autocolor "green" -}}
      {{- $labels := $issue.labels | pluck "name" | join ", " -}}
      {{- $timeAgo := timeago $issue.createdAt | autocolor "black+h" -}}
      {{- tablerow $number $issue.title $labels $timeAgo -}}
    {{- end -}}
  {{- end -}}
'

exec gh issue list "$@" --json "${JSON_FIELDS}" --template "${TEMPLATE}"
